import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

part 'app/theme.dart';
part 'app/fest_cine_app.dart';
part 'app/enums.dart';
part 'app/auth_gate.dart';
part 'app/shell.dart';
part 'features/dashboard/dashboard_page.dart';
part 'features/taquilla/taquilla_page.dart';
part 'features/eventos/event_ticket_page.dart';
part 'features/eventos/admin_events_page.dart';
part 'features/agenda/agenda_page.dart';
part 'features/reportes/reportes_page.dart';
part 'features/peliculas/admin_movies_page.dart';
part 'features/ediciones/admin_editions_page.dart';
part 'shared/widgets/common_widgets.dart';
part 'shared/widgets/style_helpers.dart';
part 'data/api_config.dart';
part 'core/utils/time_utils.dart';
part 'data/database_exception.dart';
part 'domain/models/report_models.dart';
part 'data/api_catalog.dart';
part 'data/database_gateway.dart';
part 'data/json_helpers.dart';
part 'data/mappers.dart';
part 'core/utils/seat_utils.dart';
part 'core/utils/id_utils.dart';
part 'core/utils/edition_rules.dart';
part 'core/utils/text_utils.dart';
part 'core/utils/merge_utils.dart';
part 'core/utils/fuzzy_utils.dart';
part 'core/utils/room_utils.dart';
part 'domain/models/domain_models.dart';
part 'data/fallback/catalogs.dart';

void main() => runApp(const FestCineApp());
